id = "frenixcode"
name = "FrenixCode"
description = "The open source coding agent."
version = "1.2.26"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/Hiren223344/frenix-code"

[agent_servers.frenixcode]
name = "FrenixCode"
icon = "./icons/frenixcode.svg"

[agent_servers.frenixcode.targets.darwin-aarch64]
archive = "https://github.com/Hiren223344/frenix-code/releases/download/v1.2.26/frenixcode-darwin-arm64.zip"
cmd = "./frenixcode"
args = ["acp"]

[agent_servers.frenixcode.targets.darwin-x86_64]
archive = "https://github.com/Hiren223344/frenix-code/releases/download/v1.2.26/frenixcode-darwin-x64.zip"
cmd = "./frenixcode"
args = ["acp"]

[agent_servers.frenixcode.targets.linux-aarch64]
archive = "https://github.com/Hiren223344/frenix-code/releases/download/v1.2.26/frenixcode-linux-arm64.tar.gz"
cmd = "./frenixcode"
args = ["acp"]

[agent_servers.frenixcode.targets.linux-x86_64]
archive = "https://github.com/Hiren223344/frenix-code/releases/download/v1.2.26/frenixcode-linux-x64.tar.gz"
cmd = "./frenixcode"
args = ["acp"]

[agent_servers.frenixcode.targets.windows-x86_64]
archive = "https://github.com/Hiren223344/frenix-code/releases/download/v1.2.26/frenixcode-windows-x64.zip"
cmd = "./frenixcode.exe"
args = ["acp"]
