import fs from "fs";
import path from "path";

/**
 * Frenix API Mocker: Generates high-fidelity mock data using Zod or JSON templates
 * Usage: frenix-mock <schema_name>
 */

const schemaName = process.argv[2];
if (!schemaName) {
    console.error("Usage: frenix-mock <schema_name>");
    process.exit(1);
}

const mockDir = path.resolve(process.cwd(), "src/mocks");
if (!fs.existsSync(mockDir)) fs.mkdirSync(mockDir, { recursive: true });

const template = `/**
 * Mock data for ${schemaName}
 * Generated by Frenix API Mocker
 */

export const mock${schemaName} = [
  {
    id: "uuid-1",
    name: "Sample Item 1",
    createdAt: new Date().toISOString(),
    status: "active",
  },
  {
    id: "uuid-2",
    name: "Sample Item 2",
    createdAt: new Date().toISOString(),
    status: "pending",
  }
];
`;

const targetPath = path.join(mockDir, `${schemaName.toLowerCase()}.ts`);
fs.writeFileSync(targetPath, template);

console.log(`🧪 API Mock "${schemaName}" generated: src/mocks/${schemaName.toLowerCase()}.ts`);
